### ISSUE TITLE
Doesn't work well for events from watched users

### ISSUE THREAD

**Issue by lessandro** [dforsyth/gh-girdle#3]
![see.](http://i.imgur.com/RwVpJ.png)

**Comment by dforsyth** [comment]
can you get me the markup for the 'unknown' event and the watched user events?

**Comment by lessandro** [comment]
https://gist.github.com/2860759

**Comment by dforsyth** [comment]
try this out?  https://github.com/dforsyth/gh-girdle/tree/watched_create

I guess I need to account for watched user events.  Never occurred to me since I don't watch any users.

**Comment by dforsyth** [comment]
i think this is fixed, reopen if it isn't
